server:
  port: 8586
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: WEB
          uri: http://172.23.9.9:8081
          predicates:
            - Path=/**
          order: 0
#        - id: WEB
#          uri: http://172.23.9.9:3000
#          predicates:
#            - Path=/**
#          order: 0



  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: tg-bls
            client-secret: NgiBH9T4rgvcKZLumeDl5zhSEr4U6OSv
            authorization-grant-type: authorization_code
            redirect-uri: http://172.23.9.9/auth/login/oauth2/code/keycloak
            scope:
              - email
              - profile
              - roles
              - openid
              - offline_access
        provider:
          keycloak:
            issuer-uri: http://172.23.9.9/auth/realms/Transguard
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://172.23.9.9/auth/realms/Transguard