server:
  port: 8586
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: API
          uri: http://${BLS}:${PORT_BLS}
          predicates:
            - Path=${CONTEXT_PATH}**
          order: 0
        - id: WEB
          uri: http://${FRONT}:${FRONT_PORT}
          predicates:
            - Path=/**
          order: 1



  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: tg-bls
            client-secret: NgiBH9T4rgvcKZLumeDl5zhSEr4U6OSv
            authorization-grant-type: authorization_code
            redirect-uri: http://${SERVER_IP}:${GATEWAY_PORT}/login/oauth2/code/keycloak
            scope:
              - email
              - profile
              - roles
              - openid
              - offline_access
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK}:${KEYCLOAK_PORT}/realms/Transguard
            user-name-attribute: preferred_username
      # ???????? ENV
      #??? ?? ENV
      # ???????? ENV
      #??????? ?? ENV

      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK}:${KEYCLOAK_PORT}/realms/Transguard