server:
  port: 8586
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: API
          uri: http://172.23.9.9:8081
          predicates:
            - Path=/transguard/bls
          order: 0
        - id: WEB
          uri: http://172.23.9.9:3000
          predicates:
            - Path=/**
          order: 1



  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test
            client-secret: H5MKC5u8vkzYRGWPAc1O40bfftwle6vE
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8586/login/oauth2/code/keycloak
            scope:
              - email
              - profile
              - roles
              - openid
              - offline_access
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master